# Used by the About.desktop, Activity.desktop, Docker.desktop, Omakub.desktop, and Neovim.desktop apps
include theme.conf
include font.conf
include font-size.conf

window_padding_width 30
hide_window_decorations yes
background_opacity 0.98
enable_audio_bell no
confirm_os_window_close 0

map f11 toggle_fullscreen
