foreground #a9b1d6
background #1a1b26
cursor #a9b1d6
cursor_text_color #1a1b26
selection_background #7aa2f7
url_color #7aa2f7
active_border_color #9ece6a
inactive_border_color #444b6a
bell_border_color #f7768e

color0 #32344a
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #ad8ee6
color6 #449dab
color7 #787c99
color8 #444b6a
color9 #ff7a93
color10 #b9f27c
color11 #ff9e64
color12 #7da6ff
color13 #bb9af7
color14 #0db9d7
color15 #acb0d0

window_title_bar_active_foreground #9ece6a
window_title_bar_active_background #1a1b26
window_title_bar_inactive_foreground #565f89
window_title_bar_inactive_background #1a1b26

tab_bar_background #16161e
active_tab_foreground #1a1b26
active_tab_background #9ece6a
inactive_tab_foreground #a9b1d6
inactive_tab_background #32344a
