foreground #dcd7ba
background #1f1f28
cursor #dcd7ba
cursor_text_color #1f1f28
selection_foreground #c8c093
selection_background #2d4f67
url_color #7e9cd8
active_border_color #76946a
inactive_border_color #727169
bell_border_color #c34043

color0 #090618
color1 #c34043
color2 #76946a
color3 #c0a36e
color4 #7e9cd8
color5 #957fb8
color6 #6a9589
color7 #c8c093
color8 #727169
color9 #e82424
color10 #98bb6c
color11 #e6c384
color12 #7fb4ca
color13 #938aa9
color14 #7aa89f
color15 #dcd7ba
color16 #ffa066
color17 #ff5d62

window_title_bar_active_foreground #76946a
window_title_bar_active_background #1f1f28
window_title_bar_inactive_foreground #727169
window_title_bar_inactive_background #1f1f28

tab_bar_background #16161d
active_tab_foreground #1f1f28
active_tab_background #76946a
inactive_tab_foreground #dcd7ba
inactive_tab_background #2a2a37
