foreground #d3c6aa
background #2d353b
cursor #d3c6aa
cursor_text_color #2d353b
selection_background #475258
url_color #7fbbb3
active_border_color #a7c080
inactive_border_color #475258
bell_border_color #e67e80

color0 #475258
color1 #e67e80
color2 #a7c080
color3 #dbbc7f
color4 #7fbbb3
color5 #d699b6
color6 #83c092
color7 #d3c6aa
color8 #475258
color9 #e67e80
color10 #a7c080
color11 #dbbc7f
color12 #7fbbb3
color13 #d699b6
color14 #83c092
color15 #d3c6aa

window_title_bar_active_foreground #a7c080
window_title_bar_active_background #2d353b
window_title_bar_inactive_foreground #859289
window_title_bar_inactive_background #2d353b

tab_bar_background #232a2e
active_tab_foreground #2d353b
active_tab_background #a7c080
inactive_tab_foreground #d3c6aa
inactive_tab_background #475258
